stages:
  - test
  - pages

# --- Stage Templates ----------------------------------------------------------

.test: &test

  stage: test

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build/lib/gecco/data/hmms

  before_script:
    - apt update
    - apt install -y prodigal hmmer
  script:
    - python setup.py bdist_wheel
    - pip install --upgrade dist/*.whl
    - gecco --traceback -vv run -o /tmp -g tests/data/SRR492066.fna
    - gecco --traceback -vv annotate -o /tmp -g tests/data/SRR492066.fna

# --- Stages -------------------------------------------------------------------

test:python3.7:
    image: python:3.7
    <<: *test

docs:
    image: python:3.7
    stage: pages
    script:
      - pip install .
      - pip install -r docs/requirements.txt
      - sphinx-build -b html docs public
    artifacts:
      paths:
        - public
