stages:
  - test
  - pages
  - lint

variables:
  TERM: ansi

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build/
  before_script:
    - ./ci/gitlab/test.before_script.sh
  script:
    - ./ci/gitlab/test.script.sh
  after_script:
    - python -m coverage combine
    - python -m coverage report
    - python ci/gitlab/after_script.hmmfilter.py
  # artifacts:
  #   paths:
  #     - ci/artifacts

# --- Stages -------------------------------------------------------------------

test:python3.7:
  image: python:3.7
  <<: *test

test:python3.8:
  image: python:3.8
  <<: *test

docs:
  image: python:3.8
  stage: pages
  before_script:
    - pip install -U -r docs/requirements.txt
  script:
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - public

lint:pydocstyle:
  image: python:3.8
  stage: lint
  before_script:
    - pip install -U pydocstyle
  script:
    - pydocstyle gecco

lint:mypy:
  image: python:3.8
  stage: lint
  allow_failure: true
  before_script:
    - pip install -U mypy
  script:
    - mypy gecco

lint:pylint:
  image: python:3.8
  stage: lint
  allow_failure: true
  before_script:
    - pip install -U pylint
  script:
    - pylint gecco

lint:radon:
  image: python:3.8
  stage: lint
  allow_failure: true
  before_script:
    - pip install -U radon
  script:
    - radon cc -a gecco
