stages:
  - test
  - pages
  - lint

variables:
  TERM: ansi

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - build/
  before_script:
    - python -m pip install -U wheel coverage tqdm pyhmmer
  script:
    - python setup.py build_data --inplace bdist_wheel
    - python -m pip install --find-links=dist gecco[train]
    - python -m coverage run -p -m unittest discover -vv
  after_script:
    - python -m coverage combine
    - python -m coverage xml
    - python -m coverage report
  artifacts:
    reports:
      cobertura: coverage.xml

# --- Stages -------------------------------------------------------------------

test:python3.6:
  image: python:3.6
  <<: *test

test:python3.7:
  image: python:3.7
  <<: *test

test:python3.8:
  image: python:3.8
  <<: *test

test:python3.9:
  image: python:3.9
  <<: *test

docs:
  image: python:3.9
  stage: pages
  before_script:
    - pip install -U -r docs/requirements.txt
  script:
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - public

lint:pydocstyle:
  image: python:3.9
  stage: lint
  before_script:
    - pip install -U pydocstyle
  script:
    - pydocstyle gecco

lint:mypy:
  image: python:3.9
  stage: lint
  allow_failure: true
  before_script:
    - pip install -U mypy
  script:
    - mypy gecco

lint:pylint:
  image: python:3.9
  stage: lint
  allow_failure: true
  before_script:
    - pip install -U pylint
  script:
    - pylint gecco

lint:radon:
  image: python:3.9
  stage: lint
  allow_failure: true
  before_script:
    - pip install -U radon
  script:
    - radon cc -a gecco
