stages:
  - test
  - pages
  - lint

variables:
  TERM: ansi

# --- Stage Templates ----------------------------------------------------------

.test: &test
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - ci/cache
  before_script:
    - ./ci/gitlab/test.before_script.sh
  script:
    - python setup.py bdist_wheel
    - pip install -U dist/*.whl
    - python -m coverage run -p -m unittest discover -vv
  after_script:
    - python -m coverage combine
    - python -m coverage report

# --- Stages -------------------------------------------------------------------

test:python3.7:
  image: python:3.7
  <<: *test

test:python3.8:
  image: python:3.8
  <<: *test

docs:
  image: python:3.8
  stage: pages
  before_script:
    - pip install -U -r docs/requirements.txt
  script:
    - sphinx-build -b html docs public
  artifacts:
    paths:
      - public

lint:pydocstyle:
  image: python:3.8
  stage: lint
  before_script:
    - pip install -U pydocstyle
  script:
    - pydocstyle gecco
