name: Galaxy
on:
  - push
  - pull_request

jobs:

  lint:
    name: Lint tool
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update build dependencies
      run: pip install -U wheel pip setuptools
    - name: Install planemo
      run: pip install -U planemo
    - name: Lint repository
      run: planemo shed_lint --tools ./galaxy

#   test:
#     name: Test tool
#     needs: lint
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Update build dependencies
#       run: pip install -U wheel pip setuptools
#     - name: Install planemo
#       run: pip install -U planemo
#     - name: Test tool
#       run: planemo test ./galaxy/gecco.xml

  deploy:
    environment: Tool Shed
    name: Deploy tool
#     needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update build dependencies
      run: pip install -U wheel pip setuptools
    - name: Install planemo
      run: pip install -U planemo
    - name: Deploy repository to Tool Shed
      run: planemo shed_update ./galaxy --owner althonos --name gecco -t toolshed -m '${{ github.event.head_commit.message }}' --shed_key '${{ secrets.TOOL_SHED_API_KEY }}'
      
